sudo: required

language: bash

services:
  - docker

script:
  - make test

deploy:
  provider: lambda
  function_name: "lambda-test"
  role: "arn:aws:lambda:us-east-1:523411613636:function:beckyButton"
  handler_name: "index.handler"
  access_key_id: "AWS_ACCESS_KEY_ID"
  secret_access_key: "AWS_SECRET_ACCESS_KEY"

after_success:
  - if [ "${TRAVIS_BRANCH}" == "develop" ]; then
    make -e COFFEE_BUTTON_FUNCTION_ALIAS="staging" deploy;
    fi
  - if [ "${TRAVIS_BRANCH}" == "master" ]; then
    make -e COFFEE_BUTTON_FUNCTION_ALIAS="production" deploy;
    fi
